services:
  db:
    image: mysql:8.0.36
    container_name: MYSQLDB
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password1
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf

volumes:
  mysql-data: